name: ktlint workflow

# Run this workflow every time a new commit is pushed
on:
  pull_request:
    branches:
      - main

jobs:
  linter:
    name: Ktlint code base
    runs-on: ubuntu-latest

    steps:
      - name: Clone Repo
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Run ktlint
        run: ./gradlew ktlintCheck
